#!/usr/bin/env python3
"""Write this checkout's machine-local Codex project config (.codex/config.toml, untracked).

    <env>\\Scripts\\python.exe team/setup_codex.py [--workers 6]

Run it with the Python environment that has the kit's dependencies (capstone, pyelftools, frida,
ninja). Every Codex command, subagent and `codex exec` worker opened in this checkout then gets:
- the base interpreter of that environment on PATH, with the environment's packages on PYTHONPATH.
  Sandboxed, the venv's python.exe redirector fails with "Failed to find real location".
- DQIX_KIT, DQIX_REPO and DQIX_STATE.
- git trust for the workspace, which the Windows sandbox user does not own.
- git's OpenSSL TLS backend. Sandboxed, schannel fails with SEC_E_NO_CREDENTIALS.
- write access to the folder holding the kit, the decomp and the state.
- network access.
- a subagent concurrency cap.

Rerun it after moving the workspace or the environment.
"""
import argparse
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
KIT = os.path.dirname(HERE)
sys.path.insert(0, KIT)
os.environ.setdefault("DQIX_NO_FRESHNESS", "1")
import kitpaths  # noqa: E402


def q(s):
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def git_root():
    """<Git for Windows root> from `git --exec-path` (<root>/mingw64/libexec/git-core)."""
    r = subprocess.run(["git", "--exec-path"], capture_output=True, text=True)
    p = os.path.normpath(r.stdout.strip())
    for _ in range(3):
        p = os.path.dirname(p)
    return p if os.path.isdir(os.path.join(p, "usr", "bin")) else None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--workers", type=int, default=6)
    a = ap.parse_args()
    for mod in ("capstone", "elftools", "ninja"):
        __import__(mod)
    scripts = os.path.dirname(sys.executable)
    base = os.path.dirname(getattr(sys, "_base_executable", sys.executable))
    site = os.path.join(sys.prefix, "Lib", "site-packages")
    roots = {os.path.dirname(p) for p in (KIT, kitpaths.REPO, kitpaths.SP)}
    if len(roots) != 1:
        sys.exit(f"keep the kit, the decomp and the state in one folder; found {sorted(roots)}")
    workspace = roots.pop()
    path = [base, scripts]
    git = git_root()
    if git:
        path += [os.path.join(git, "usr", "bin"), os.path.join(git, "bin")]
    seen, parts = set(), []
    for p in path + os.environ.get("PATH", "").split(os.pathsep):
        k = p.lower().rstrip("\\/")
        if p and k not in seen and "/" not in p:
            seen.add(k)
            parts.append(p)
    env = {
        "PATH": os.pathsep.join(parts),
        "PYTHONPATH": site,
        "DQIX_KIT": KIT,
        "DQIX_REPO": os.path.normpath(kitpaths.REPO),
        "DQIX_STATE": os.path.normpath(kitpaths.SP),
        "PYTHONUTF8": "1",
        "GIT_CONFIG_COUNT": "2",
        "GIT_CONFIG_KEY_0": "safe.directory",
        "GIT_CONFIG_VALUE_0": "*",
        "GIT_CONFIG_KEY_1": "http.sslBackend",
        "GIT_CONFIG_VALUE_1": "openssl",
    }
    lines = [
        "# Generated by team/setup_codex.py for this machine. Untracked; rerun it to regenerate.",
        'sandbox_mode = "workspace-write"',
        "",
        "[sandbox_workspace_write]",
        "network_access = true",
        f"writable_roots = [{q(os.path.normpath(workspace))}]",
        "",
        "[agents]",
        f"max_concurrent_threads_per_session = {a.workers}",
        "",
        "[shell_environment_policy]",
        'inherit = "all"',
        "",
        "[shell_environment_policy.set]",
    ] + [f"{k} = {q(v)}" for k, v in env.items()]
    os.makedirs(os.path.join(KIT, ".codex"), exist_ok=True)
    out = os.path.join(KIT, ".codex", "config.toml")
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out}")
    print(f"python  {os.path.join(base, 'python.exe')} (+ {site})")
    print(f"write   {workspace}")


main()
